// !!! This is a file automatically generated by hipify!!!
#include <c10/hip/HIPMiscFunctions.h>
#include <c10/util/env.h>

namespace c10::hip {

// NOLINTNEXTLINE(bugprone-exception-escape,-warnings-as-errors)
const char* get_hip_check_suffix() noexcept {
  static auto device_blocking_flag =
      c10::utils::check_env("AMD_SERIALIZE_KERNEL");
  static bool blocking_enabled =
      (device_blocking_flag.has_value() && device_blocking_flag.value());
  if (blocking_enabled) {
    return "";
  } else {
    return "\nHIP kernel errors might be asynchronously reported at some"
           " other API call, so the stacktrace below might be incorrect."
           "\nFor debugging consider passing AMD_SERIALIZE_KERNEL=3";
  }
}
std::mutex* getFreeMutex() {
  static std::mutex hip_free_mutex;
  return &hip_free_mutex;
}

} // namespace c10::hip
